# permissions for end users to edit kudremukhs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kudremukh-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kudremukh-operator
    app.kubernetes.io/part-of: kudremukh-operator
    app.kubernetes.io/managed-by: kustomize
  name: kudremukh-editor-role
rules:
- apiGroups:
  - sevenport.io.my.domain
  resources:
  - kudremukhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sevenport.io.my.domain
  resources:
  - kudremukhs/status
  verbs:
  - get
