apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kudremukh-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Pod is the Schema for the pods API
      displayName: Pod
      kind: Pod
      name: pods.sevenport.io.my.domain
      version: v1alpha1
  description: a simple pod reconciler
  displayName: kudremukh-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - pod
  - reconcile
  links:
  - name: Kudremukh Operator
    url: https://kudremukh-operator.domain
  maturity: alpha
  provider:
    name: sevenport-labs
  version: 0.0.0
